baseURL = 'https://zumafi.com/'
languageCode = 'en-us'
title = 'Surgeons Aid ☘️'

enableEmoji = true
theme = 'hugo-book'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
